package releasecontract

import (
	"strings"
	"testing"
	"time"
)

func validBinding() Binding{return Binding{SchemaVersion:"1.0.0",Repository:"owner/repo",BaseRevision:"base",FinalRevision:"final",RequirementDigest:"requirements",ChangeSetDigest:"change",PolicyRevision:"policy",TestAttestationsDigest:"tests",ReviewAttestationsDigest:"reviews",DecisionAttestationsDigest:"decisions",ChangedPaths:[]string{"change.go"}}}
func validAttestations()Attestations{now:=time.Date(2026,8,12,0,0,0,0,time.UTC);return Attestations{Tests:[]Test{{ID:"acceptance",Repository:"owner/repo",RunID:"test-run",RequirementIDs:[]string{"R1"},Revision:"final",Status:"PASS",ArtifactDigest:"artifact",ActorRunID:"test-actor",StartedAt:now,FinishedAt:now}},Reviews:[]Review{{ID:"independent",Repository:"owner/repo",ReviewerRunID:"review-run",ReviewerContextID:"review-context",ChangeAuthorRunID:"build-run",ChangeAuthorContextID:"build-context",BaseRevision:"base",FinalRevision:"final",RequirementDigest:"requirements",ChangeSetDigest:"change",PolicyRevision:"policy",ReviewedPaths:[]string{"change.go"},Status:"PASS"}},Decisions:[]Decision{{Repository:"owner/repo",FinalRevision:"final",RequirementDigest:"requirements",ChangeSetDigest:"change",PolicyRevision:"policy",Kind:"RELEASE_RISK",Authority:"human",Subject:"final",Status:"APPROVED"}}}}
func validGates()PolicyGates{return PolicyGates{PolicyRevision:"policy",RequiredTests:[]string{"acceptance"},RequiredReviews:[]string{"independent"},RequiredDecisions:[]string{"RELEASE_RISK"}}}
func validChange()ChangeSet{return ChangeSet{SchemaVersion:"1.0.0",BaseRevision:"base",FinalRevision:"final",ChangedPaths:[]string{"change.go"}}}

func TestValidateAcceptsPolicyRequiredRevisionBoundEvidence(t *testing.T){a:=validAttestations();if err:=validBinding().Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err!=nil{t.Fatal(err)}}
func TestValidateRejectsEmptyEvidence(t *testing.T){b:=validBinding();a:=validAttestations();a.Tests=nil;a.Reviews=nil;a.Decisions=nil;if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err==nil{t.Fatal("expected empty evidence rejection")}}
func TestValidateDoesNotLetEvidenceDeclareItselfOptional(t *testing.T){b:=validBinding();a:=validAttestations();a.Tests[0].Status="PLANNED";if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"not an executed pass"){t.Fatalf("expected policy gate rejection, got %v",err)}}
func TestValidateRejectsPolicyWithNoRequiredGates(t *testing.T){b:=validBinding();g:=validGates();g.RequiredTests=nil;if err:=b.Validate(g,validChange(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"no required test"){t.Fatalf("expected empty policy rejection, got %v",err)}}
func TestValidateRejectsDuplicateAndUnknownEvidence(t *testing.T){b:=validBinding();b.Tests=append(b.Tests,a.Tests[0]);if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"duplicate"){t.Fatalf("expected duplicate rejection, got %v",err)};b=validBinding();a.Tests[0].Status="SUCCESS";if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"unknown status"){t.Fatalf("expected status rejection, got %v",err)}}
func TestValidateRejectsStalePartialAndCorrelatedReview(t *testing.T){b:=validBinding();a:=validAttestations();a.Reviews[0].FinalRevision="old";if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"stale"){t.Fatalf("expected stale rejection, got %v",err)};b=validBinding();a.Reviews[0].ReviewedPaths=nil;if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"changed scope"){t.Fatalf("expected scope rejection, got %v",err)};b=validBinding();a.Reviews[0].ReviewerContextID=a.Reviews[0].ChangeAuthorContextID;if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"not independent"){t.Fatalf("expected correlation rejection, got %v",err)}}
func TestValidateRejectsUntypedAndNonWaivableExceptions(t *testing.T){b:=validBinding();b.Exceptions=[]Exception{{Kind:"CORRECTNESS",Approver:"human",Subject:"failure",Rationale:"ship",Scope:[]string{"R1"},ExpiresAt:time.Now().Add(time.Hour)}};if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Now());err==nil||!strings.Contains(err.Error(),"not waivable"){t.Fatalf("expected exception rejection, got %v",err)};b=validBinding();a.Decisions[0].Kind="CODE_APPROVAL";if err:=b.Validate(validGates(),validChange(),a,"owner/repo","final",time.Now());err==nil||!strings.Contains(err.Error(),"human decision"){t.Fatalf("expected decision rejection, got %v",err)}}
