package releasecontract
import("strings";"testing";"time")
func binding()Binding{return Binding{SchemaVersion:"1.0.0",Repository:"owner/repo",BaseRevision:"base",FinalRevision:"final",RequirementDigest:"requirements",ChangeSetDigest:"change",PolicyRevision:"policy",TestAttestationsDigest:"tests",ReviewAttestationsDigest:"reviews",DecisionAttestationsDigest:"decisions",ChangedPaths:[]string{"change.go"}}}
func gates()PolicyGates{return PolicyGates{RequiredTests:[]string{"test"},RequiredReviews:[]string{"review"},RequiredDecisions:[]string{"RELEASE_RISK"}}}
func change()ChangeSet{return ChangeSet{SchemaVersion:"1.0.0",BaseRevision:"base",FinalRevision:"final",ChangedPaths:[]string{"change.go"}}}
func attest()Attestations{now:=time.Now();return Attestations{Tests:[]Test{{ID:"test",Repository:"owner/repo",RunID:"run",RequirementIDs:[]string{"R1"},Revision:"final",Status:"PASS",ArtifactDigest:"digest",ActorRunID:"actor",StartedAt:now,FinishedAt:now}},Reviews:[]Review{{ID:"review",Repository:"owner/repo",ReviewerRunID:"reviewer",ReviewerContextID:"review-context",ChangeAuthorRunID:"author",ChangeAuthorContextID:"author-context",BaseRevision:"base",FinalRevision:"final",RequirementDigest:"requirements",ChangeSetDigest:"change",PolicyRevision:"policy",ReviewedPaths:[]string{"change.go"},Status:"PASS"}},Decisions:[]Decision{{Repository:"owner/repo",FinalRevision:"final",RequirementDigest:"requirements",ChangeSetDigest:"change",PolicyRevision:"policy",Kind:"RELEASE_RISK",Authority:"human",Subject:"final",Status:"APPROVED"}}}}
func TestValidateAttestations(t *testing.T){if err:=binding().Validate(gates(),change(),attest(),"owner/repo","final",time.Time{});err!=nil{t.Fatal(err)}}
func TestRejectsEmptyAttestations(t *testing.T){if err:=binding().Validate(gates(),change(),Attestations{},"owner/repo","final",time.Time{});err==nil{t.Fatal("expected rejection")}}
func TestRejectsStaleAttestation(t *testing.T){a:=attest();a.Tests[0].Revision="old";if err:=binding().Validate(gates(),change(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"another revision"){t.Fatalf("got %v",err)}}
func TestRejectsCrossRepositoryAttestation(t *testing.T){a:=attest();a.Tests[0].Repository="fork/repo";if err:=binding().Validate(gates(),change(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"another repository"){t.Fatalf("got %v",err)}}
func TestRejectsCorrelatedReview(t *testing.T){a:=attest();a.Reviews[0].ReviewerContextID=a.Reviews[0].ChangeAuthorContextID;if err:=binding().Validate(gates(),change(),a,"owner/repo","final",time.Time{});err==nil||!strings.Contains(err.Error(),"not independent"){t.Fatalf("got %v",err)}}
