package approval
import("crypto/ed25519";"crypto/sha256";"encoding/base64";"encoding/hex";"encoding/json";"errors";"io";"regexp")
type Manifest struct{SchemaVersion string `json:"schema_version"`;Repository string `json:"repository"`;FinalRevision string `json:"final_revision"`;BindingDigest string `json:"binding_digest"`;PolicyDigest string `json:"policy_digest"`;RequirementsDigest string `json:"requirements_digest"`;ChangeSetDigest string `json:"change_set_digest"`;TestDigest string `json:"test_attestations_digest"`;ReviewDigest string `json:"review_attestations_digest"`;DecisionDigest string `json:"decision_attestations_digest"`}
var sha40=regexp.MustCompile(`^[0-9a-f]{40}$`);var sha64=regexp.MustCompile(`^[0-9a-f]{64}$`);var repo=regexp.MustCompile(`^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$`)
func Parse(body []byte)(Manifest,error){var m Manifest;if err:=strict(body,&m);err!=nil{return m,err};if m.SchemaVersion!="1.0.0"||!repo.MatchString(m.Repository)||!sha40.MatchString(m.FinalRevision){return m,errors.New("approval manifest metadata is invalid")};for _,d:=range []string{m.BindingDigest,m.PolicyDigest,m.RequirementsDigest,m.ChangeSetDigest,m.TestDigest,m.ReviewDigest,m.DecisionDigest}{if !sha64.MatchString(d){return m,errors.New("approval manifest digest is invalid")}};return m,nil}
func VerifyBytes(manifest,signatureText,keyText []byte)error{signature,err:=base64.StdEncoding.DecodeString(string(trim(signatureText)));if err!=nil{return err};key,err:=base64.StdEncoding.DecodeString(string(trim(keyText)));if err!=nil{return err};if len(key)!=ed25519.PublicKeySize||!ed25519.Verify(ed25519.PublicKey(key),manifest,signature){return errors.New("approval signature verification failed")};return nil}
func DigestBytes(body []byte)string{sum:=sha256.Sum256(body);return hex.EncodeToString(sum[:])}
func strict(body []byte,target any)error{d:=json.NewDecoder(bytesReader(body));d.DisallowUnknownFields();if err:=d.Decode(target);err!=nil{return err};var x any;if err:=d.Decode(&x);!errors.Is(err,io.EOF){return errors.New("unexpected trailing JSON")};return nil}
type reader struct{b []byte;i int};func bytesReader(b []byte)*reader{return &reader{b:b}};func(r *reader)Read(p []byte)(int,error){if r.i>=len(r.b){return 0,io.EOF};n:=copy(p,r.b[r.i:]);r.i+=n;return n,nil}
func trim(v []byte)[]byte{s,e:=0,len(v);for s<e&&(v[s]==' '||v[s]=='\n'||v[s]=='\r'||v[s]=='\t'){s++};for e>s&&(v[e-1]==' '||v[e-1]=='\n'||v[e-1]=='\r'||v[e-1]=='\t'){e--};return v[s:e]}
