package policyset
import("strings";"testing";"time")
func TestResolvePreservesFloorAndAdditions(t *testing.T){o:=Policy{SchemaVersion:"1.0.0",Revision:"o",Commands:[]Command{{ID:"test",Executable:"go",Required:true}}};r:=Policy{SchemaVersion:"1.0.0",Revision:"r",Commands:[]Command{{ID:"lint",Executable:"lint",Required:true}}};got,err:=Resolve(o,r,time.Date(2026,8,12,0,0,0,0,time.UTC));if err!=nil||len(got.Commands)!=2||len(got.Delta)!=1{t.Fatalf("%+v %v",got,err)}}
func TestResolveRejectsDuplicateAndNonWaivableWeakening(t *testing.T){o:=Policy{SchemaVersion:"1.0.0",Revision:"o",Commands:[]Command{{ID:"test",Executable:"go",Required:true,NonWaivable:true}}};r:=Policy{SchemaVersion:"1.0.0",Revision:"r",Commands:[]Command{{ID:"test",Executable:"go"},{ID:"test",Executable:"go"}}};if _,err:=Resolve(o,r,time.Date(2026,8,12,0,0,0,0,time.UTC));err==nil||!strings.Contains(err.Error(),"non-waivable"){t.Fatalf("%v",err)}}
func TestResolveAllowsTypedException(t *testing.T){o:=Policy{SchemaVersion:"1.0.0",Revision:"o",Commands:[]Command{{ID:"test",Executable:"go",Required:true}}};r:=Policy{SchemaVersion:"1.0.0",Revision:"r",Commands:[]Command{{ID:"test",Executable:"go"}},Exceptions:[]Exception{{CommandID:"test",Approver:"owner",Rationale:"temporary",ExpiresAt:"2026-09-01T00:00:00Z"}}};if _,err:=Resolve(o,r,time.Date(2026,8,12,0,0,0,0,time.UTC));err!=nil{t.Fatal(err)}}
func TestResolveRejectsDuplicateRepositoryIDs(t *testing.T){o:=Policy{SchemaVersion:"1.0.0",Revision:"o"};r:=Policy{SchemaVersion:"1.0.0",Revision:"r",Commands:[]Command{{ID:"x",Executable:"go"},{ID:"x",Executable:"go"}}};if _,err:=Resolve(o,r,time.Date(2026,8,12,0,0,0,0,time.UTC));err==nil||!strings.Contains(err.Error(),"duplicate"){t.Fatalf("%v",err)}}

func TestResolveRejectsExpiredException(t *testing.T){o:=Policy{SchemaVersion:"1.0.0",Revision:"o",Commands:[]Command{{ID:"x",Executable:"go",Required:true}}};r:=Policy{SchemaVersion:"1.0.0",Revision:"r",Commands:[]Command{{ID:"x",Executable:"go"}},Exceptions:[]Exception{{CommandID:"x",Approver:"a",Rationale:"r",ExpiresAt:"2020-01-01T00:00:00Z"}};if _,err:=Resolve(o,r,time.Now());err==nil{t.Fatal("expected expired rejection")}}
func TestResolveEmitsStrengthening(t *testing.T){o:=Policy{SchemaVersion:"1.0.0",Revision:"o",Commands:[]Command{{ID:"x",Executable:"go"}}};r:=Policy{SchemaVersion:"1.0.0",Revision:"r",Commands:[]Command{{ID:"x",Executable:"go",Required:true}}};got,err:=Resolve(o,r,time.Time{});if err!=nil||!got.Commands[0].Required||got.Commands[0].Provenance!="organization+repository"{t.Fatalf("%+v %v",got,err)}}
