package policyset
import("encoding/json";"errors";"fmt";"io";"os";"sort")
type Command struct{ID string `json:"id"`;Executable string `json:"executable"`;Args []string `json:"args"`;Required bool `json:"required"`;NonWaivable bool `json:"non_waivable,omitempty"`}
type Exception struct{CommandID string `json:"command_id"`;Approver string `json:"approver"`;Rationale string `json:"rationale"`;ExpiresAt string `json:"expires_at"`}
type Policy struct{SchemaVersion string `json:"schema_version"`;Revision string `json:"revision"`;Commands []Command `json:"commands"`;Exceptions []Exception `json:"exceptions,omitempty"`}
type Resolved struct{SchemaVersion string `json:"schema_version"`;OrganizationRevision string `json:"organization_revision"`;RepositoryRevision string `json:"repository_revision"`;Commands []ResolvedCommand `json:"commands"`;Delta []string `json:"delta"`}
type ResolvedCommand struct{Command;Provenance string `json:"provenance"`}
func Load(path string)(Policy,error){var p Policy;err:=strict(path,&p);return p,err}
func Resolve(org,repo Policy)(Resolved,error){if org.SchemaVersion!="1.0.0"||repo.SchemaVersion!="1.0.0"||org.Revision==""||repo.Revision==""{return Resolved{},errors.New("policy metadata is incomplete")};exceptions:=map[string]Exception{};for _,e:=range repo.Exceptions{if e.CommandID==""||e.Approver==""||e.Rationale==""||e.ExpiresAt==""||exceptions[e.CommandID].CommandID!=""{return Resolved{},errors.New("policy exception is invalid or duplicated")};exceptions[e.CommandID]=e};seen:=map[string]Command{};repoSeen:=map[string]bool{};out:=Resolved{SchemaVersion:"1.0.0",OrganizationRevision:org.Revision,RepositoryRevision:repo.Revision,Commands:[]ResolvedCommand{},Delta:[]string{}};for _,c:=range org.Commands{if c.ID==""||c.Executable==""||seen[c.ID].ID!=""{return Resolved{},errors.New("organization policy has invalid or duplicate command")};seen[c.ID]=c;out.Commands=append(out.Commands,ResolvedCommand{c,"organization"})};for _,c:=range repo.Commands{if c.ID==""||c.Executable==""||repoSeen[c.ID]{return Resolved{},errors.New("repository policy has invalid or duplicate command")};repoSeen[c.ID]=true;if base,ok:=seen[c.ID];ok{if base.Executable!=c.Executable||fmt.Sprint(base.Args)!=fmt.Sprint(c.Args){return Resolved{},fmt.Errorf("conflicting command id %q",c.ID)};if base.Required&&!c.Required{if base.NonWaivable{return Resolved{},fmt.Errorf("non-waivable command %q cannot be weakened",c.ID)};if exceptions[c.ID].CommandID==""{return Resolved{},fmt.Errorf("repository weakens required command %q without approved exception",c.ID)};out.Delta=append(out.Delta,"exception:"+c.ID)};continue};seen[c.ID]=c;out.Commands=append(out.Commands,ResolvedCommand{c,"repository"});out.Delta=append(out.Delta,c.ID)};sort.Slice(out.Commands,func(i,j int)bool{return out.Commands[i].ID<out.Commands[j].ID});sort.Strings(out.Delta);return out,nil}
func strict(path string,target any)error{f,err:=os.Open(path);if err!=nil{return err};defer f.Close();d:=json.NewDecoder(f);d.DisallowUnknownFields();if err:=d.Decode(target);err!=nil{return err};var x any;if err:=d.Decode(&x);!errors.Is(err,io.EOF){return errors.New("unexpected trailing JSON")};return nil}
