package policyset
import("clean-code/internal/approval";"encoding/json";"errors";"io";"os";"sort";"time")
type Command struct{ID string `json:"id"`;Executable string `json:"executable"`;Args []string `json:"args"`;Required bool `json:"required"`;NonWaivable bool `json:"non_waivable,omitempty"`}
type Policy struct{SchemaVersion string `json:"schema_version"`;Revision string `json:"revision"`;Commands []Command `json:"commands"`}
type ExceptionApproval struct{SchemaVersion string `json:"schema_version"`;OrganizationDigest string `json:"organization_digest"`;RepositoryDigest string `json:"repository_digest"`;CommandID string `json:"command_id"`;Scope string `json:"scope"`;ExpiresAt string `json:"expires_at"`;Approver string `json:"approver"`}
type Resolved struct{SchemaVersion string `json:"schema_version"`;OrganizationRevision string `json:"organization_revision"`;RepositoryRevision string `json:"repository_revision"`;Commands []ResolvedCommand `json:"commands"`;Delta []string `json:"delta"`};type ResolvedCommand struct{Command;Provenance string `json:"provenance"`}
func ParsePolicy(body []byte)(Policy,error){var p Policy;err:=strict(body,&p);return p,err};func ParseApproval(body []byte)(ExceptionApproval,error){var a ExceptionApproval;err:=strict(body,&a);return a,err}
func VerifyException(body,sig,key []byte,a ExceptionApproval,orgDigest,repoDigest,command string,now time.Time)error{if err:=approval.VerifyBytes(body,sig,key);err!=nil{return err};expiry,err:=time.Parse(time.RFC3339,a.ExpiresAt);if err!=nil||!expiry.After(now)||a.SchemaVersion!="1.0.0"||a.OrganizationDigest!=orgDigest||a.RepositoryDigest!=repoDigest||a.CommandID!=command||a.Scope!="required"||a.Approver==""{return errors.New("policy weakening approval is invalid")};return nil}
func Resolve(org,repo Policy,approved map[string]bool)(Resolved,error){if org.SchemaVersion!="1.0.0"||repo.SchemaVersion!="1.0.0"||org.Revision==""||repo.Revision==""{return Resolved{},errors.New("policy metadata is incomplete")};seen:=map[string]Command{};repoSeen:=map[string]bool{};out:=Resolved{"1.0.0",org.Revision,repo.Revision,[]ResolvedCommand{},[]string{}};for _,c:=range org.Commands{if c.ID==""||c.Executable==""||seen[c.ID].ID!=""{return Resolved{},errors.New("organization policy has invalid or duplicate command")};seen[c.ID]=c;out.Commands=append(out.Commands,ResolvedCommand{c,"organization"})};for _,c:=range repo.Commands{if c.ID==""||c.Executable==""||repoSeen[c.ID]{return Resolved{},errors.New("repository policy has invalid or duplicate command")};repoSeen[c.ID]=true;if base,ok:=seen[c.ID];ok{if base.Executable!=c.Executable||!sameArgs(base.Args,c.Args){return Resolved{},errors.New("conflicting command id "+c.ID)};if base.Required&&!c.Required{if base.NonWaivable||!approved[c.ID]{return Resolved{},errors.New("required command weakening is not approved")};for i:=range out.Commands{if out.Commands[i].ID==c.ID{out.Commands[i]=ResolvedCommand{c,"organization+signed-exception"}}};out.Delta=append(out.Delta,"exception:"+c.ID)}else if !base.Required&&c.Required{for i:=range out.Commands{if out.Commands[i].ID==c.ID{out.Commands[i]=ResolvedCommand{c,"organization+repository"}}};out.Delta=append(out.Delta,"strengthened:"+c.ID)};continue};out.Commands=append(out.Commands,ResolvedCommand{c,"repository"});out.Delta=append(out.Delta,c.ID)};sort.Slice(out.Commands,func(i,j int)bool{return out.Commands[i].ID<out.Commands[j].ID});sort.Strings(out.Delta);return out,nil}
func sameArgs(a,b []string)bool{if len(a)!=len(b){return false};for i:=range a{if a[i]!=b[i]{return false}};return true}
func strict(body []byte,target any)error{d:=json.NewDecoder(bytesReader(body));d.DisallowUnknownFields();if err:=d.Decode(target);err!=nil{return err};var x any;if err:=d.Decode(&x);!errors.Is(err,io.EOF){return errors.New("unexpected trailing JSON")};return nil}
type reader struct{b []byte;i int};func bytesReader(b []byte)*reader{return &reader{b:b}};func(r *reader)Read(p []byte)(int,error){if r.i>=len(r.b){return 0,io.EOF};n:=copy(p,r.b[r.i:]);r.i+=n;return n,nil}
func Load(path string)(Policy,error){body,err:=os.ReadFile(path);if err!=nil{return Policy{},err};return ParsePolicy(body)}
