package sloppiness

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAssessReturnsBoundedRepairBrief(t *testing.T) {
	root := t.TempDir()
	for index, name := range []string{"a.go", "b.go", "c.go"} {
		content := "package sample\n\nfunc work() {\n\tprintln(\"value\") // TODO tracked nowhere\n}\n"
		if err := os.WriteFile(filepath.Join(root, name), []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		_ = index
	}

	first, err := Assess(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if first.Cycle.Status != "REPAIR" || first.Cycle.Pass != 1 || first.Cycle.MaxPasses != 2 {
		t.Fatalf("unexpected first cycle: %+v", first.Cycle)
	}
	if first.Score == 0 || len(first.Findings) == 0 {
		t.Fatalf("expected scored findings: %+v", first)
	}
	for _, finding := range first.Findings {
		if finding.Instruction == "" || finding.Verification == "" || finding.ID == "" {
			t.Fatalf("finding is not actionable: %+v", finding)
		}
	}

	second, err := Assess(root, &first)
	if err != nil {
		t.Fatal(err)
	}
	if second.Cycle.Status != "ESCALATE" || second.Cycle.Pass != 2 {
		t.Fatalf("assessment must stop after pass two: %+v", second.Cycle)
	}
	if !strings.Contains(second.Cycle.NextAction, "Stop rewriting") {
		t.Fatalf("missing explicit stop instruction: %q", second.Cycle.NextAction)
	}
}

func TestAssessIgnoresGeneratedAndReportsDone(t *testing.T) {
	root := t.TempDir()
	generated := "// Code generated by fixture. DO NOT EDIT.\n// TODO does not count\n"
	if err := os.WriteFile(filepath.Join(root, "generated.go"), []byte(generated), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "small.go"), []byte("package sample\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	report, err := Assess(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if report.Cycle.Status != "DONE" || report.Score != 0 || len(report.Findings) != 0 {
		t.Fatalf("expected a clean evidence report: %+v", report)
	}
}

func TestLoadRejectsUnknownFieldsAndSchemas(t *testing.T) {
	if _, err := Load(strings.NewReader(`{"schema_version":"1.0.0","extra":true}`)); err == nil {
		t.Fatal("expected unknown field to fail")
	}
	if _, err := Load(strings.NewReader(`{"schema_version":"0.9.0"}`)); err == nil {
		t.Fatal("expected old schema to fail")
	}
}
