package study
import("errors";"sort")
type Task struct{ID string `json:"id"`;Model string `json:"model"`;Tools []string `json:"tools"`;Limit int `json:"limit"`;Oracle string `json:"oracle"`}
type Manifest struct{SchemaVersion string `json:"schema_version"`;StudyID string `json:"study_id"`;MinimumPairs int `json:"minimum_pairs"`;Tasks []Task `json:"tasks"`}
type Outcome struct{TaskID string `json:"task_id"`;Arm string `json:"arm"`;Status string `json:"status"`;FalsePositives int `json:"false_positives"`;CorrectSilence bool `json:"correct_silence"`}
type Results struct{SchemaVersion string `json:"schema_version"`;StudyID string `json:"study_id"`;Outcomes []Outcome `json:"outcomes"`}
type Report struct{SchemaVersion string `json:"schema_version"`;Pairs int `json:"pairs"`;ClaimAllowed bool `json:"claim_allowed"`;Outcomes []Outcome `json:"outcomes"`;Limitations []string `json:"limitations"`}
func Score(m Manifest,r Results)(Report,error){if m.SchemaVersion!="1.0.0"||r.SchemaVersion!="1.0.0"||m.StudyID==""||m.StudyID!=r.StudyID||m.MinimumPairs<1{return Report{},errors.New("study metadata is invalid")};tasks:=map[string]Task{};for _,t:=range m.Tasks{if t.ID==""||t.Model==""||len(t.Tools)==0||t.Limit<1||t.Oracle==""||tasks[t.ID].ID!=""{return Report{},errors.New("preregistered task is invalid")};tasks[t.ID]=t};arms:=map[string]map[string]bool{};for _,o:=range r.Outcomes{if tasks[o.TaskID].ID==""||!one(o.Arm,"control","workflow")||!one(o.Status,"PASS","FAIL","TIMEOUT"){return Report{},errors.New("raw outcome is invalid")};if arms[o.TaskID]==nil{arms[o.TaskID]=map[string]bool{}};if arms[o.TaskID][o.Arm]{return Report{},errors.New("duplicate study arm")};arms[o.TaskID][o.Arm]=true};pairs:=0;for id:=range tasks{if arms[id]["control"]&&arms[id]["workflow"]{pairs++}};limits:=[]string{};allowed:=pairs>=m.MinimumPairs&&pairs==len(tasks);if !allowed{limits=append(limits,"insufficient or unbalanced paired cases; performance claims are blocked")};sort.Slice(r.Outcomes,func(i,j int)bool{if r.Outcomes[i].TaskID==r.Outcomes[j].TaskID{return r.Outcomes[i].Arm<r.Outcomes[j].Arm};return r.Outcomes[i].TaskID<r.Outcomes[j].TaskID});return Report{SchemaVersion:"1.0.0",Pairs:pairs,ClaimAllowed:allowed,Outcomes:r.Outcomes,Limitations:limits},nil}
func one(v string,a ...string)bool{for _,x:=range a{if v==x{return true}};return false}
