package study
import("encoding/json";"errors";"io";"os";"sort";"strings")
type Task struct{ID string `json:"id"`;Model string `json:"model"`;Tools []string `json:"tools"`;Limit int `json:"limit"`;Oracle string `json:"oracle"`}
type Manifest struct{SchemaVersion string `json:"schema_version"`;StudyID string `json:"study_id"`;Repository string `json:"repository"`;Revision string `json:"revision"`;MinimumPairs int `json:"minimum_pairs"`;Tasks []Task `json:"tasks"`}
type Outcome struct{Repository string `json:"repository"`;Revision string `json:"revision"`;RunID string `json:"run_id"`;ArtifactDigest string `json:"artifact_digest"`;StartedAt string `json:"started_at"`;FinishedAt string `json:"finished_at"`;TaskID string `json:"task_id"`;Arm string `json:"arm"`;Model string `json:"model"`;Tools []string `json:"tools"`;Limit int `json:"limit"`;Oracle string `json:"oracle"`;Status string `json:"status"`;FalsePositives int `json:"false_positives"`;CorrectSilence bool `json:"correct_silence"`}
type Results struct{SchemaVersion string `json:"schema_version"`;StudyID string `json:"study_id"`;Outcomes []Outcome `json:"outcomes"`}
type Report struct{SchemaVersion string `json:"schema_version"`;Pairs int `json:"pairs"`;ClaimAllowed bool `json:"claim_allowed"`;Outcomes []Outcome `json:"outcomes"`;Limitations []string `json:"limitations"`}
func ParseResults(body []byte)(Results,error){var r Results;d:=json.NewDecoder(strings.NewReader(string(body)));d.DisallowUnknownFields();err:=d.Decode(&r);return r,err};func LoadManifest(path string)(Manifest,error){var m Manifest;err:=load(path,&m);return m,err};func LoadResults(path string)(Results,error){var r Results;err:=load(path,&r);return r,err};func load(path string,target any)error{f,err:=os.Open(path);if err!=nil{return err};defer f.Close();d:=json.NewDecoder(f);d.DisallowUnknownFields();if err:=d.Decode(target);err!=nil{return err};var x any;if err:=d.Decode(&x);!errors.Is(err,io.EOF){return errors.New("unexpected trailing JSON")};return nil}
func Score(m Manifest,r Results)(Report,error){if m.SchemaVersion!="1.0.0"||r.SchemaVersion!="1.0.0"||m.StudyID==""||m.StudyID!=r.StudyID||m.MinimumPairs<1{return Report{},errors.New("study metadata is invalid")};tasks:=map[string]Task{};for _,t:=range m.Tasks{if t.ID==""||t.Model==""||len(t.Tools)==0||t.Limit<1||t.Oracle==""||tasks[t.ID].ID!=""{return Report{},errors.New("preregistered task is invalid")};tasks[t.ID]=t};arms:=map[string]map[string]bool{};failed:=false;for _,o:=range r.Outcomes{if o.Status=="FAIL"||o.Status=="TIMEOUT"{failed=true};task:=tasks[o.TaskID];if task.ID==""||o.Repository!=m.Repository||o.Revision!=m.Revision||o.RunID==""||o.ArtifactDigest==""||o.StartedAt==""||o.FinishedAt==""||o.FalsePositives<0||o.Model!=task.Model||o.Limit!=task.Limit||o.Oracle!=task.Oracle||!same(o.Tools,task.Tools)||!one(o.Arm,"control","workflow")||!one(o.Status,"PASS","FAIL","TIMEOUT"){return Report{},errors.New("raw outcome is invalid")};if arms[o.TaskID]==nil{arms[o.TaskID]=map[string]bool{}};if arms[o.TaskID][o.Arm]{return Report{},errors.New("duplicate study arm")};arms[o.TaskID][o.Arm]=true};pairs:=0;for id:=range tasks{if arms[id]["control"]&&arms[id]["workflow"]{pairs++}};limits:=[]string{};allowed:=pairs>=m.MinimumPairs&&pairs==len(tasks)&&!failed;if !allowed{limits=append(limits,"insufficient or unbalanced paired cases; performance claims are blocked")};sort.Slice(r.Outcomes,func(i,j int)bool{if r.Outcomes[i].TaskID==r.Outcomes[j].TaskID{return r.Outcomes[i].Arm<r.Outcomes[j].Arm};return r.Outcomes[i].TaskID<r.Outcomes[j].TaskID});return Report{SchemaVersion:"1.0.0",Pairs:pairs,ClaimAllowed:allowed,Outcomes:r.Outcomes,Limitations:limits},nil}
func same(a,b []string)bool{if len(a)!=len(b){return false};for i:=range a{if a[i]!=b[i]{return false}};return true}
func one(v string,a ...string)bool{for _,x:=range a{if v==x{return true}};return false}
